### ISSUE TITLE
Configurable location for Jekyll config file location

### ISSUE THREAD

**Issue by paulrobertlloyd** [voxpelli/webpage-micropub-to-github#17]
This project is fascinating, and opening my eyes to the myriad possibilities of publishing directly to/from my GitHub repos, so thanks so much for putting this together!

Right now I have my repo set-up such that posts are located within `src/_posts/` and my config is located at `etc/jekyll/config.yml`. If I could point this service to the location of my config file, my thinking is the source location for content (`src`) could then be detected, posts written to the correct folder, rather than defaulting to root of my repo.

**Comment by voxpelli** [comment]
Thanks!

Making the path to the config file configurable would be fairly simple.

One would add a new optional value to the site config: https://github.com/voxpelli/webpage-micropub-to-github/blob/3340b6f5425c3f2fbc5915de86daa0dfe0d3f8f1/lib/sites.js#L10

And then have that carry through to the auto-config somewhere here: https://github.com/voxpelli/webpage-micropub-to-github/blob/3340b6f5425c3f2fbc5915de86daa0dfe0d3f8f1/lib/handler.js#L47

And then use it there to replace the hard-coded `_config.yml`: https://github.com/voxpelli/webpage-micropub-to-github/blob/ee672f6d26812f425a431bd983bab3e09fd65908/lib/auto-config.js#L35

Using the info in there to alter the source location of content would certainly be doable then, as the option pointed out in #18 is sent in using the result from the auto-config.

I can try to find time to take a look at it in the weekend 🙂

**Comment by RosemaryOrchard** [comment]
I tried setting the `MICROPUB_FILENAME_STYLE` for the page location, and Heroku throws a wobbly whatever I do.

Could someone give me a pointer on what I'm doing wrong? I am trying to configure this to use with Grav, not Jekyll - hence the completely different file path. I have tried file paths starting with `/`, `_`, and letters.

`2018-03-28T06:29:15.963367+00:00 app[web.1]: > micropub-to-github@0.6.1 start /app
2018-03-28T06:29:15.963369+00:00 app[web.1]: > node .
2018-03-28T06:29:15.963371+00:00 app[web.1]: 
2018-03-28T06:29:16.593182+00:00 app[web.1]: undefined:1
2018-03-28T06:29:16.593220+00:00 app[web.1]: pages/blog/:year-:month-:day-:slug/blogpost.md
2018-03-28T06:29:16.593222+00:00 app[web.1]: ^
2018-03-28T06:29:16.593224+00:00 app[web.1]: 
2018-03-28T06:29:16.593226+00:00 app[web.1]: SyntaxError: Unexpected token p in JSON at position 0
2018-03-28T06:29:16.593228+00:00 app[web.1]:     at JSON.parse (<anonymous>)
2018-03-28T06:29:16.593230+00:00 app[web.1]:     at parseJSON (/app/lib/config.js:22:59)
2018-03-28T06:29:16.593232+00:00 app[web.1]:     at Object.<anonymous> (/app/lib/config.js:53:20)
2018-03-28T06:29:16.593233+00:00 app[web.1]:     at Module._compile (module.js:649:30)
2018-03-28T06:29:16.593235+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:660:10)
2018-03-28T06:29:16.593236+00:00 app[web.1]:     at Module.load (module.js:561:32)
2018-03-28T06:29:16.593238+00:00 app[web.1]:     at tryModuleLoad (module.js:501:12)
2018-03-28T06:29:16.593239+00:00 app[web.1]:     at Function.Module._load (module.js:493:3)
2018-03-28T06:29:16.593241+00:00 app[web.1]:     at Module.require (module.js:593:17)
2018-03-28T06:29:16.593243+00:00 app[web.1]:     at require (internal/module.js:11:18)
2018-03-28T06:29:16.600163+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2018-03-28T06:29:16.600503+00:00 app[web.1]: npm ERR! errno 1
2018-03-28T06:29:16.601476+00:00 app[web.1]: npm ERR! micropub-to-github@0.6.1 start: `node .`
2018-03-28T06:29:16.601625+00:00 app[web.1]: npm ERR! Exit status 1
2018-03-28T06:29:16.601840+00:00 app[web.1]: npm ERR! 
2018-03-28T06:29:16.602002+00:00 app[web.1]: npm ERR! Failed at the micropub-to-github@0.6.1 start script.
2018-03-28T06:29:16.602183+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-03-28T06:29:16.608195+00:00 app[web.1]: 
2018-03-28T06:29:16.608351+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2018-03-28T06:29:16.608424+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2018-03-28T06_29_16_603Z-debug.log
2018-03-28T06:29:16.680967+00:00 heroku[web.1]: State changed from starting to crashed
2018-03-28T06:29:16.669653+00:00 heroku[web.1]: Process exited with status 1
2018-03-28T06:29:52.637868+00:00 app[api]: Remove MICROPUB_FILENAME_STYLE config vars by user rosenewsletters42@gmail.com2018-03-28T06:29:52.637868+00:00 app[api]: Release v15 created by user rosenewsletters42@gmail.com2018-03-28T06:29:53.061459+00:00 heroku[web.1]: State changed from crashed to starting
2018-03-28T06:29:55.188644+00:00 heroku[web.1]: Starting process with command `npm start`
2018-03-28T06:29:57.200914+00:00 app[web.1]: 
2018-03-28T06:29:57.200960+00:00 app[web.1]: > micropub-to-github@0.6.1 start /app
2018-03-28T06:29:57.200962+00:00 app[web.1]: > node .
2018-03-28T06:29:57.200964+00:00 app[web.1]: 
2018-03-28T06:29:57.853756+00:00 heroku[web.1]: State changed from starting to up
2018-03-28T06:29:57.822137+00:00 app[web.1]: Started and listens on 43300`
