### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by paulrobertlloyd** [voxpelli/webpage-micropub-to-github#21]
I was unable to push up my changes to Heroku, as the `prepush` script calls `npm test` which for me was failing. I’m not sure why… I wonder if it’s because the test script uses dummy authentication values? i.e.:

```
const token = 'abc123';
const user = 'username';
const repo = 'repo';

filename = filename || '_posts/2015-06-30-awesomeness-is-awesome.md';
```

I had to delete the `prepush` command in order to push my changes to Heroku.

This is the error I get:

```
> micropub-to-github@0.6.0 test /Users/paulrobertlloyd/Sites/paulrobertlloyd-micropub
> installed-check -e && eslint . && npm run dependency-check && npm run mocha


> micropub-to-github@0.6.0 dependency-check /Users/paulrobertlloyd/Sites/paulrobertlloyd-micropub
> JS_FILES="lib/*.js test/*.js" && dependency-check . $JS_FILES && dependency-check . $JS_FILES --unused --no-dev

Success! All dependencies used in the code are listed in package.json
Success! All dependencies in package.json are used in the code

> micropub-to-github@0.6.0 mocha /Users/paulrobertlloyd/Sites/paulrobertlloyd-micropub
> NODE_ENV=test DOTENV_FILE=test/test.env istanbul cover _mocha -- -u exports -R spec test/**/*.spec.js



  Handler
    main
      1) should format and send content
      2) should upload files prior to content
      ✓ should override existing content if matching URL
GitHub Error {}
      ✓ should not override existing content if no matching URL
      3) should set a custom commit message when formatter returns a category
      4) should format HTML to Markdown and send content
      5) should support category deriving
      6) should support callback based permalink style
      7) should support callback based filename style


  2 passing (66ms)
  7 failing

  1) Handler main should format and send content:
     VError: Failed to call GitHub: request to https://api.github.com/repos/username/repo/contents/_posts/2015-06-30-awesomeness-is-awesome.md failed, reason: Nock: No match for request {
  "method": "PUT",
  "url": "https://api.github.com/repos/username/repo/contents/_posts/2015-06-30-awesomeness-is-awesome.md",
  "headers": {
    "content-type": [
      "application/json"
    ],
    "authorization": [
      "Bearer abc123"
    ],
    "accept": [
      "application/vnd.github.v3+json"
    ],
    "user-agent": [
      "username"
    ],
    "accept-encoding": [
      "gzip,deflate"
    ],
    "connection": [
      "close"
    ],
    "content-length": [
      236
    ]
  },
  "body": "{\"message\":\"uploading article\",\"content\":\"LS0tCmxheW91dDogbWljcm9wdWJwb3N0CmRhdGU6ICcyMDE1LTA2LTMwVDE0OjE5OjQ1LjAwMFonCnRpdGxlOiBhd2Vzb21lbmVzcyBpcyBhd2Vzb21lCmxhbmc6IGVuCnNsdWc6IGF3ZXNvbWVuZXNzLWlzLWF3ZXNvbWUKLS0tCmhlbGxvIHdvcmxkCg==\"}"
}
      at putRequest.then.then.catch.err (node_modules/github-publish/index.js:118:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

  2) Handler main should upload files prior to content:
     VError: Failed to call GitHub: request to https://api.github.com/repos/username/repo/contents/media/2015-06-awesomeness-is-awesome/foo.jpg failed, reason: Nock: No match for request {
  "method": "PUT",
  "url": "https://api.github.com/repos/username/repo/contents/media/2015-06-awesomeness-is-awesome/foo.jpg",
  "headers": {
    "content-type": [
      "application/json"
    ],
    "authorization": [
      "Bearer abc123"
    ],
    "accept": [
      "application/vnd.github.v3+json"
    ],
    "user-agent": [
      "username"
    ],
    "accept-encoding": [
      "gzip,deflate"
    ],
    "connection": [
      "close"
    ],
    "content-length": [
      50
    ]
  },
  "body": "{\"message\":\"uploading media\",\"content\":\"YWJjMTIz\"}"
}
      at putRequest.then.then.catch.err (node_modules/github-publish/index.js:118:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

  3) Handler main should set a custom commit message when formatter returns a category:
     VError: Failed to call GitHub: request to https://api.github.com/repos/username/repo/contents/_posts/2015-06-30-51585.md failed, reason: Nock: No match for request {
  "method": "PUT",
  "url": "https://api.github.com/repos/username/repo/contents/_posts/2015-06-30-51585.md",
  "headers": {
    "content-type": [
      "application/json"
    ],
    "authorization": [
      "Bearer abc123"
    ],
    "accept": [
      "application/vnd.github.v3+json"
    ],
    "user-agent": [
      "username"
    ],
    "accept-encoding": [
      "gzip,deflate"
    ],
    "connection": [
      "close"
    ],
    "content-length": [
      223
    ]
  },
  "body": "{\"message\":\"uploading social interaction\",\"content\":\"LS0tCmxheW91dDogbWljcm9wdWJwb3N0CmRhdGU6ICcyMDE1LTA2LTMwVDE0OjE5OjQ1LjAwMFonCnRpdGxlOiAnJwpsYW5nOiBlbgpzbHVnOiAnNTE1ODUnCmNhdGVnb3J5OiBzb2NpYWwKLS0tCmhlbGxvIHdvcmxkCg==\"}"
}
      at putRequest.then.then.catch.err (node_modules/github-publish/index.js:118:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

  4) Handler main should format HTML to Markdown and send content:
     VError: Failed to call GitHub: request to https://api.github.com/repos/username/repo/contents/_posts/2015-06-30-awesomeness-is-awesome.md failed, reason: Nock: No match for request {
  "method": "PUT",
  "url": "https://api.github.com/repos/username/repo/contents/_posts/2015-06-30-awesomeness-is-awesome.md",
  "headers": {
    "content-type": [
      "application/json"
    ],
    "authorization": [
      "Bearer abc123"
    ],
    "accept": [
      "application/vnd.github.v3+json"
    ],
    "user-agent": [
      "username"
    ],
    "accept-encoding": [
      "gzip,deflate"
    ],
    "connection": [
      "close"
    ],
    "content-length": [
      240
    ]
  },
  "body": "{\"message\":\"uploading article\",\"content\":\"LS0tCmxheW91dDogbWljcm9wdWJwb3N0CmRhdGU6ICcyMDE1LTA2LTMwVDE0OjE5OjQ1LjAwMFonCnRpdGxlOiBhd2Vzb21lbmVzcyBpcyBhd2Vzb21lCmxhbmc6IGVuCnNsdWc6IGF3ZXNvbWVuZXNzLWlzLWF3ZXNvbWUKLS0tCioqaGVsbG8gd29ybGQqKgo=\"}"
}
      at putRequest.then.then.catch.err (node_modules/github-publish/index.js:118:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

  5) Handler main should support category deriving:
     VError: Failed to call GitHub: request to https://api.github.com/repos/username/repo/contents/_posts/2015-06-30-awesomeness-is-awesome.md failed, reason: Nock: No match for request {
  "method": "PUT",
  "url": "https://api.github.com/repos/username/repo/contents/_posts/2015-06-30-awesomeness-is-awesome.md",
  "headers": {
    "content-type": [
      "application/json"
    ],
    "authorization": [
      "Bearer abc123"
    ],
    "accept": [
      "application/vnd.github.v3+json"
    ],
    "user-agent": [
      "username"
    ],
    "accept-encoding": [
      "gzip,deflate"
    ],
    "connection": [
      "close"
    ],
    "content-length": [
      248
    ]
  },
  "body": "{\"message\":\"uploading xyz\",\"content\":\"LS0tCmxheW91dDogbWljcm9wdWJwb3N0CmRhdGU6ICcyMDE1LTA2LTMwVDE0OjE5OjQ1LjAwMFonCnRpdGxlOiBhd2Vzb21lbmVzcyBpcyBhd2Vzb21lCmxhbmc6IGVuCnNsdWc6IGF3ZXNvbWVuZXNzLWlzLWF3ZXNvbWUKY2F0ZWdvcnk6IHh5egotLS0KaGVsbG8gd29ybGQK\"}"
}
      at putRequest.then.then.catch.err (node_modules/github-publish/index.js:118:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

  6) Handler main should support callback based permalink style:
     VError: Failed to call GitHub: request to https://api.github.com/repos/username/repo/contents/_posts/2015-06-30-awesomeness-is-awesome.md failed, reason: Nock: No match for request {
  "method": "PUT",
  "url": "https://api.github.com/repos/username/repo/contents/_posts/2015-06-30-awesomeness-is-awesome.md",
  "headers": {
    "content-type": [
      "application/json"
    ],
    "authorization": [
      "Bearer abc123"
    ],
    "accept": [
      "application/vnd.github.v3+json"
    ],
    "user-agent": [
      "username"
    ],
    "accept-encoding": [
      "gzip,deflate"
    ],
    "connection": [
      "close"
    ],
    "content-length": [
      236
    ]
  },
  "body": "{\"message\":\"uploading article\",\"content\":\"LS0tCmxheW91dDogbWljcm9wdWJwb3N0CmRhdGU6ICcyMDE1LTA2LTMwVDE0OjE5OjQ1LjAwMFonCnRpdGxlOiBhd2Vzb21lbmVzcyBpcyBhd2Vzb21lCmxhbmc6IGVuCnNsdWc6IGF3ZXNvbWVuZXNzLWlzLWF3ZXNvbWUKLS0tCmhlbGxvIHdvcmxkCg==\"}"
}
      at putRequest.then.then.catch.err (node_modules/github-publish/index.js:118:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

  7) Handler main should support callback based filename style:
     VError: Failed to call GitHub: request to https://api.github.com/repos/username/repo/contents/second/awesomeness-is-awesome.md failed, reason: Nock: No match for request {
  "method": "PUT",
  "url": "https://api.github.com/repos/username/repo/contents/second/awesomeness-is-awesome.md",
  "headers": {
    "content-type": [
      "application/json"
    ],
    "authorization": [
      "Bearer abc123"
    ],
    "accept": [
      "application/vnd.github.v3+json"
    ],
    "user-agent": [
      "username"
    ],
    "accept-encoding": [
      "gzip,deflate"
    ],
    "connection": [
      "close"
    ],
    "content-length": [
      236
    ]
  },
  "body": "{\"message\":\"uploading article\",\"content\":\"LS0tCmxheW91dDogbWljcm9wdWJwb3N0CmRhdGU6ICcyMDE1LTA2LTMwVDE0OjE5OjQ1LjAwMFonCnRpdGxlOiBhd2Vzb21lbmVzcyBpcyBhd2Vzb21lCmxhbmc6IGVuCnNsdWc6IGF3ZXNvbWVuZXNzLWlzLWF3ZXNvbWUKLS0tCmhlbGxvIHdvcmxkCg==\"}"
}
      at putRequest.then.then.catch.err (node_modules/github-publish/index.js:118:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)



=============================================================================
Writing coverage object [/Users/paulrobertlloyd/Sites/paulrobertlloyd-micropub/coverage/coverage.json]
Writing coverage reports at [/Users/paulrobertlloyd/Sites/paulrobertlloyd-micropub/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 64.47% ( 49/76 )
Branches     : 52.78% ( 19/36 )
Functions    : 80% ( 4/5 )
Lines        : 66.67% ( 48/72 )
================================================================================
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! micropub-to-github@0.6.0 mocha: `NODE_ENV=test DOTENV_FILE=test/test.env istanbul cover _mocha -- -u exports -R spec test/**/*.spec.js`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the micropub-to-github@0.6.0 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/paulrobertlloyd/.npm/_logs/2017-07-08T19_29_47_292Z-debug.log
npm ERR! Test failed.  See above for more details.
```

**Comment by voxpelli** [comment]
To ignore the tests when pushing you can do:

```bash
git push heroku master --no-verify
```

Regarding the tests:

* Which version of Node are you running?
* And have you changed anything in the code you are pushing?

Because those tests there simulate full micropub requests and ensures that it's formatted and uploaded to GitHub correctly by matching it towards a mocked GitHub API. That means that if you have changed how you are formatting things, then naturally the tests will point out that the formatted content doesn't match any more.

The fix then would be to update the base64 encoded content in the tests to expect the correct data – and one would easiest do that by logging the attempted request, inspect that it's correct, and then updating the tests.

I can give a more exact pointer if you want to adapt the tests to your changes – or else you can just do a `--no-verify` when deploying if you're okay with not having tests for any adaptions you have made (assuming that it is the reason)

**Comment by voxpelli** [comment]
If you're using Node 8, then nock (the library used to mock the GitHub API) isn't currently working correctly there: https://github.com/node-nock/nock/issues/922

It's failing for 8 on Travis as well: https://travis-ci.org/voxpelli/webpage-micropub-to-github/jobs/251757274

**Comment by paulrobertlloyd** [comment]
Aaah, I am running Node 8, so that’ll explain it! The only change I made was to remove the `prepush` script from `package.json`, but using `--no-verify` is a better approach. Hopefully upstream fixes to nock will arrive soon.
