### ISSUE TITLE
Does the library support the Micropub Media Endpoint?

### ISSUE THREAD

**Issue by maggerbo** [voxpelli/webpage-micropub-to-github#28]
I'm trying to use Micro.Blog to post via my endpoint hosted on Heroku. But the micro.blog app keep asking for a Media Endpoint which the Heroku endpoint doesn't provide.

Does the library support it? Or am I doing something wrong?

Thanks.

**Comment by voxpelli** [comment]
This matches https://github.com/voxpelli/node-micropub-express/issues/11

**Comment by brandontreb** [comment]
I'd also love to hear how/if this is supported? I have hacked in 

`config['media-endpoint'] = MY_ENDPOINT`

and it now passes micro.blog's basic endpoint check.  However, when trying to post, I still get 'Photo URL was blank' from the micro.blog client. It should be noted that I can use Quil successfully.

This is in the Heroku log

`2018-04-29T21:48:00.357468+00:00 app[web.1]: Error: Unexpected field
2018-04-29T21:48:00.357480+00:00 app[web.1]:     at makeError (/app/node_modules/multer/lib/make-error.js:12:13)
2018-04-29T21:48:00.357482+00:00 app[web.1]:     at wrappedFileFilter (/app/node_modules/multer/index.js:40:19)
2018-04-29T21:48:00.357487+00:00 app[web.1]:     at Busboy.<anonymous> (/app/node_modules/multer/lib/make-middleware.js:114:7)
2018-04-29T21:48:00.357489+00:00 app[web.1]:     at Busboy.emit (events.js:182:13)
2018-04-29T21:48:00.357491+00:00 app[web.1]:     at Busboy.emit (/app/node_modules/busboy/lib/main.js:38:33)
2018-04-29T21:48:00.357493+00:00 app[web.1]:     at PartStream.<anonymous> (/app/node_modules/busboy/lib/types/multipart.js:213:13)
2018-04-29T21:48:00.357494+00:00 app[web.1]:     at PartStream.emit (events.js:182:13)
2018-04-29T21:48:00.357496+00:00 app[web.1]:     at HeaderParser.<anonymous> (/app/node_modules/dicer/lib/Dicer.js:51:16)
2018-04-29T21:48:00.357497+00:00 app[web.1]:     at HeaderParser.emit (events.js:182:13)
2018-04-29T21:48:00.357499+00:00 app[web.1]:     at HeaderParser._finish (/app/node_modules/dicer/lib/HeaderParser.js:68:8)`

Any help would be greatly appreciated.

Cheers!

**Comment by maxandersen** [comment]
I wonder what the "support media upload" from readme refers to if not media-endpoint ? and yeah, looking at the code there is no support for media uploads in posts.

**Comment by voxpelli** [comment]
@maxandersen Originally, at the time the first version of this project, media was uploaded as part of the post request itself, so that’s what’s still supported.

A media endpoint is the highest priority for this project, I hope I can get some time for it soon.
