### ISSUE TITLE
Can't publish posts due to duplicate key error

### ISSUE THREAD

**Issue by bltavares** [voxpelli/webpage-micropub-to-github#65]
Hello,

First of all, thanks for this project. I'm trying it out using the provided Heroku button, and whenever I try to use one of the micropub clients online, I received the following message:

<details>
<summary>Logs</summary>

```
2018-09-07T01:22:03.594889+00:00 app[web.1]: { micropubDocument:

2018-09-07T01:22:03.594916+00:00 app[web.1]:    '{\n  "properties": {\n    "name": [\n      "hehehe"\n    ],\n    "content": [\n      {\n        "html": "<p>\\n  heheheheheh\\n  <br />\\n</p>"\n      }\n    ]\n  },\n  "type": [\n    "h-entry"\n  ]\n}',

2018-09-07T01:22:03.594919+00:00 app[web.1]:   date:

2018-09-07T01:22:03.594921+00:00 app[web.1]:    'Fri Sep 07 2018 01:22:03 GMT+0000 (Coordinated Universal Time)' } 'Received a Micropub document'

2018-09-07T01:22:03.596198+00:00 app[web.1]: VError: Error in post handling: duplicated mapping key at line 54, column -32:

2018-09-07T01:22:03.596201+00:00 app[web.1]:     kramdown:

2018-09-07T01:22:03.596203+00:00 app[web.1]:     ^

2018-09-07T01:22:03.596205+00:00 app[web.1]:     at Promise.resolve.then.then.catch.err (/app/node_modules/micropub-express/index.js:391:14)

2018-09-07T01:22:03.596206+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:68:7)
```
</details>

I didn't have much time yet to drill down what could lead to this issue, but I thought of documenting it anyway. I'll see if I can debug this latter and send some contribution if I find why this is failing.

Thanks!

**Comment by jbpyn** [comment]
Check your _config.yml,  'kramdown' must be in there twice
